#
# MindTouch Î»#
# Copyright (C) 2018-2019 MindTouch, Inc.
# www.mindtouch.com  oss@mindtouch.com
#
# For community documentation and downloads visit mindtouch.com;
# please review the licensing section.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
AWSTemplateFormatVersion: 2010-09-09
Description: LambdaSharp Tool (v%%VERSION%%)
Parameters:

  DeploymentBucketName:
    Type: String
    Description: Name of an existing S3 bucket for LambdaSharp deployments (if blank, a new S3 bucket is created)
    AllowedPattern: '[a-z0-9\-]*'
    ConstraintDescription: Must only contain lowercase alphanumeric characters or left blank

  RequestedBucketName:
    Type: String
    Description: (optional) Name of newly created S3 bucket (if blank, a unique name is generated)
    AllowedPattern: '[a-z0-9\-]*'
    ConstraintDescription: Must only contain lowercase alphanumeric characters or left blank

  DeploymentNotificationTopic:
    Type: String
    Description: ARN of existing SNS topic for CloudFormation notifications (if blank, an SNS topic is created)
    AllowedPattern: '(arn:aws:sns:.*)?'
    ConstraintDescription: Must be an SNS topic ARN or left blank

  LambdaSharpToolVersion:
    Type: String
    Description: LambdaSharpTool version
    AllowedPattern: '\d+.\d+(.\d+(.\d+)?)?(-[\w]+)?'
    ConstraintDescription: 'Version number must have format: Major.Minor[.Build[.Revision]]'

  LambdaSharpToolProfile:
    Type: String
    Description: LambdaSharpTool profile
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9_\-]*'
    ConstraintDescription: Must begin with a valid identifier

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: LambdaSharp Deployment Settings
        Parameters:
          - DeploymentBucketName
          - RequestedBucketName
          - DeploymentNotificationTopic
      - Label:
          default: LambdaSharp Tool Settings
        Parameters:
          - LambdaSharpToolProfile
          - LambdaSharpToolVersion
    ParameterLabels:
      DeploymentBucketName:
        default: Name of an existing S3 bucket for LambdaSharp deployments (if blank, a new S3 bucket is created)
      RequestedBucketName:
        default: (optional) Name of newly created S3 bucket (if blank, a unique name is generated)
      DeploymentNotificationTopic:
        default: ARN of existing SNS topic for CloudFormation notifications (if blank, an SNS topic is created)
      LambdaSharpToolVersion:
        default: LambdaSharpTool version
      LambdaSharpToolProfile:
        default: LambdaSharpTool profile

Conditions:
  DeploymentBucketNameIsEmpty: !Equals [ !Ref DeploymentBucketName, "" ]
  RequestedBucketNameIsEmpty: !Equals [ !Ref RequestedBucketName, "" ]
  CreateDeploymentNotificationTopic: !Equals [ !Ref DeploymentNotificationTopic, "" ]

Resources:

  # LambdaSharpTool settings
  VersionSsmParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub '/LambdaSharpTool/${LambdaSharpToolProfile}/Version'
      Description: LambdaSharp module version
      Type: String
      Value: !Ref LambdaSharpToolVersion

  StackNameSsmParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub '/LambdaSharpTool/${LambdaSharpToolProfile}/StackName'
      Description: LambdaSharp CloudFormation stack name
      Type: String
      Value: !Ref AWS::StackName

  # S3 Deployment Bucket & Path
  DeploymentBucket:
    Type: AWS::S3::Bucket
    Condition: DeploymentBucketNameIsEmpty
    Properties:
      BucketName: !If
        - RequestedBucketNameIsEmpty
        - !Ref AWS::NoValue
        - !Ref RequestedBucketName

  DeploymentBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Condition: DeploymentBucketNameIsEmpty
    Properties:
      Bucket: !Ref DeploymentBucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: serverlessrepo.amazonaws.com
            Action: s3:GetObject
            Resource: !Sub "arn:aws:s3:::${DeploymentBucket}/*"

  DeploymentBucketNameSsmParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub '/LambdaSharpTool/${LambdaSharpToolProfile}/DeploymentBucketName'
      Description: S3 bucket name to publish modules
      Type: String
      Value: !If
        - DeploymentBucketNameIsEmpty
        - !Ref DeploymentBucket
        - !Ref DeploymentBucketName

  # SNS CloudFormation Notification Topic
  DeploymentNotificationTopicResource:
    Type: AWS::SNS::Topic
    Condition: CreateDeploymentNotificationTopic

  DeploymentNotificationTopicSsmParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub '/LambdaSharpTool/${LambdaSharpToolProfile}/DeploymentNotificationTopic'
      Description: SNS topic for CloudFormation notifications
      Type: String
      Value: !If
        - CreateDeploymentNotificationTopic
        - !Ref DeploymentNotificationTopicResource
        - !Ref DeploymentNotificationTopic

  # S3 Module Buckets
  ModuleBucketNamesSsmParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub '/LambdaSharpTool/${LambdaSharpToolProfile}/ModuleBucketNames'
      Description: S3 bucket names to search for modules
      Type: String
      Value: !Join
        - ","
        - - !If
            - DeploymentBucketNameIsEmpty
            - !Ref DeploymentBucket
            - !Ref DeploymentBucketName
          - lambdasharp-${AWS::Region}
