AWSTemplateFormatVersion: 2010-09-09
Description: LambdaSharp Core Resources (v%%VERSION%%)

##############
# Parameters #
##############
Parameters:

  BucketName:
    Type: String
    Description: ARN of an existing S3 bucket for LambdaSharp deployments (leave blank to create a new bucket)
    AllowedPattern: '^[a-z0-9][a-z0-9-]{1,61}[a-z0-9]$'
    ConstraintDescription: Bucket name must be 3 to 63 characters long, with lowercase alphanumeric characters at the beginning and end

#############
# Resources #
#############
Resources:

  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName

  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref Bucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:

          - Sid: AnonymousAccess
            Effect: Allow
            Principal: "*"
            Action:
              - s3:ListBucket
              - s3:GetObject
            Resource:
              - !GetAtt Bucket.Arn
              - !Sub "${Bucket.Arn}/*"
