# MindTouch Î»#
# Copyright (C) 2018 MindTouch, Inc.
# www.mindtouch.com  oss@mindtouch.com
#
# For community documentation and downloads visit mindtouch.com;
# please review the licensing section.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

Module: LambdaSharp
Version: 0.4
Description: LambdaSharp Runtime
Pragmas:
  - no-runtime-version-check
  - no-lambdasharp-dependencies
  - no-module-registration

Inputs:

  # LambdaSharp Tier Settings
  - Parameter: DeadLetterQueueArn
    Section: LambdaSharp Tier Settings
    Label: Dead Letter Queue (ARN)
    Description: Dead letter queue for functions (leave blank to create a new queue)
    Default: ""
    Resource:
      Type: AWS::SQS::Queue
      Allow: None

  - Parameter: LoggingStreamArn
    Section: LambdaSharp Tier Settings
    Label: Logging Stream (ARN)
    Description: Logging kinesis stream for functions (leave blank to create a new stream)
    Default: ""
    Resource:
      Type: AWS::Kinesis::Stream
      Properties:
        RetentionPeriodHours: !Ref LoggingStreamRetentionPeriod
        ShardCount: 1

  - Parameter: LoggingStreamRetentionPeriod
    Section: LambdaSharp Tier Settings
    Label: Retention period (hours)
    Description: How long logging stream entries are kept before they are lost
    Default: 24

  - Parameter: DefaultSecretKeyArn
    Section: LambdaSharp Tier Settings
    Label: Default Secret Key (ARN)
    Description: Default secret key for functions (leave blank to create a new key)
    Default: ""
    Resource:
      Type: AWS::KMS::Key
      Properties:
        Description: Default encryption/decryption key for LambdaSharp modules
        EnableKeyRotation: !Ref DefaultSecretKeyRotationEnabled
        KeyPolicy:
          Version: "2012-10-17"
          Id: !Sub "${AWS::StackName}ModuleDefaultSecretKeyPolicy"
          Statement:
            - Effect: Allow
              Principal:
                AWS: !Sub "arn:aws:iam::${AWS::AccountId}:root"
              Action:
                - kms:*
              Resource: "*"

  - Parameter: DefaultSecretKeyRotationEnabled
    Section: LambdaSharp Tier Settings
    Label: Enable key rotation
    Description: Rotate KMS key automatically every 365 days
    Default: false

  # Rollbar Settings
  - Parameter: RollbarReadAccessToken
    Type: Secret
    Section: Rollbar Settings
    Label: Read Access Token
    Description: Account-level token for read operations
    Default: ""

  - Parameter: RollbarWriteAccessToken
    Type: Secret
    Section: Rollbar Settings
    Label: Write Access Token
    Description: Account-level token for write operations
    Default: ""

  - Parameter: RollbarProjectPrefix
    Section: Rollbar Settings
    Label: Project Prefix
    Description: Optional prefix when creating Rollbar projects
    Default: ""

  # Module Registration Table Settings
  - Parameter: RegistrationTableReadCapacity
    Section: Module Registration Table Settings
    Label: Read Capacity Units
    Description: Provisioned read capacity for registrations table
    Default: 1

  - Parameter: RegistrationTableWriteCapacity
    Section: Module Registration Table Settings
    Label: Write Capacity Units
    Description: Provisioned write capacity for registrations table
    Default: 1

Outputs:

  - Export: DeadLetterQueueArn
    Description: LambdaSharp Dead Letter Queue

  - Export: LoggingStreamArn
    Description: LambdaSharp Logging Stream

  - Export: DefaultSecretKeyArn
    Description: LambdaSharp Default Secrets Key

  - Export: ErrorReportTopic
    Description: SNS topic for LambdaSharp module errors
    Value: !GetAtt Registrar.Outputs.ErrorReportTopic

  - Export: UsageReportTopic
    Description: SNS topic for LambdaSharp function usage reports
    Value: !GetAtt Registrar.Outputs.UsageReportTopic

Variables:

  - Var: DefaultSecretKeyAlias
    Resource:
      Type: AWS::KMS::Alias
      Properties:
        AliasName: !Sub "alias/${DeploymentPrefix}LambdaSharpDefaultSecretKey"
        TargetKeyId: !Ref DefaultSecretKeyArn

  - Var: Registrar
    Description: LambdaSharp Modules and Functions Registrar
    Resource:
      Type: AWS::CloudFormation::Stack
      Properties:
        NotificationARNS: !Ref AWS::NotificationARNs
        Parameters:
          RollbarReadAccessToken: !Ref RollbarReadAccessToken
          RollbarWriteAccessToken: !Ref RollbarWriteAccessToken
          RollbarProjectPrefix: !Ref RollbarProjectPrefix
          RegistrationTableReadCapacity: !Ref RegistrationTableReadCapacity
          RegistrationTableWriteCapacity: !Ref RegistrationTableWriteCapacity
          Secrets: !Ref Secrets
          LambdaSharpDeadLetterQueueArn: !Ref DeadLetterQueueArn
          LambdaSharpLoggingStreamArn: !Ref LoggingStreamArn
          LambdaSharpDefaultSecretKeyArn: !Ref DefaultSecretKeyArn
          DeploymentBucketName: !Ref DeploymentBucketName
          DeploymentPrefix: !Ref DeploymentPrefix
          DeploymentPrefixLowercase: !Ref DeploymentPrefixLowercase
          DeploymentParent: !Ref AWS::StackName
        TemplateURL: !Sub "https://${DeploymentBucketName}.s3.${AWS::Region}.amazonaws.com/Modules/LambdaSharpRegistrar/Versions/${Module::Version}/cloudformation.json"
        TimeoutInMinutes: 5

  - Var: S3Subscriber
    Description: LambdaSharp S3 Lambda Function Subscriber
    Resource:
      Type: AWS::CloudFormation::Stack
      DependsOn: Registrar
      Properties:
        NotificationARNS: !Ref AWS::NotificationARNs
        Parameters:
          Secrets: !Ref Secrets
          LambdaSharpDeadLetterQueueArn: !Ref DeadLetterQueueArn
          LambdaSharpLoggingStreamArn: !Ref LoggingStreamArn
          LambdaSharpDefaultSecretKeyArn: !Ref DefaultSecretKeyArn
          DeploymentBucketName: !Ref DeploymentBucketName
          DeploymentPrefix: !Ref DeploymentPrefix
          DeploymentPrefixLowercase: !Ref DeploymentPrefixLowercase
          DeploymentParent: !Ref AWS::StackName
        TemplateURL: !Sub "https://${DeploymentBucketName}.s3.${AWS::Region}.amazonaws.com/Modules/LambdaSharpS3Subscriber/Versions/${Module::Version}/cloudformation.json"
        TimeoutInMinutes: 5

  - Var: S3PackageLoader
    Description: LambdaSharp S3 Package Loader
    Resource:
      Type: AWS::CloudFormation::Stack
      DependsOn: Registrar
      Properties:
        NotificationARNS: !Ref AWS::NotificationARNs
        Parameters:
          Secrets: !Ref Secrets
          LambdaSharpDeadLetterQueueArn: !Ref DeadLetterQueueArn
          LambdaSharpLoggingStreamArn: !Ref LoggingStreamArn
          LambdaSharpDefaultSecretKeyArn: !Ref DefaultSecretKeyArn
          DeploymentBucketName: !Ref DeploymentBucketName
          DeploymentPrefix: !Ref DeploymentPrefix
          DeploymentPrefixLowercase: !Ref DeploymentPrefixLowercase
          DeploymentParent: !Ref AWS::StackName
        TemplateURL: !Sub "https://${DeploymentBucketName}.s3.${AWS::Region}.amazonaws.com/Modules/LambdaSharpS3PackageLoader/Versions/${Module::Version}/cloudformation.json"
        TimeoutInMinutes: 5
