# LambdaSharp (Î»#)
# Copyright (C) 2018-2022
# lambdasharp.net
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

Module: Sample.DynamoDBNative
Description: A sample module using the LambdaSharp.DynamoDB.Native assembly
Items:

  - Function: ApiFunction
    Memory: 1769
    Timeout: 30
    Sources:

      - Api: POST:/customers
        Invoke: CreateCustomer

      - Api: PUT:/customers/{customerUsername}/{addressLabel}
        Invoke: AddOrUpdateAddress

      - Api: GET:/customers/{customerUsername}
        Invoke: GetCustomerWithMostRecentOrders

      - Api: POST:/orders
        Invoke: SaveOrder

      - Api: PUT:/orders
        Invoke: UpdateOrder

      - Api: GET:/orders/{orderId}
        Invoke: GetOrderWithOrderItems

  - Resource: DataTable
    Scope: ApiFunction
    Type: AWS::DynamoDB::Table
    Allow: Subscribe
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:

        - AttributeName: PK
          AttributeType: S

        - AttributeName: SK
          AttributeType: S

        - AttributeName: GSI1PK
          AttributeType: S

        - AttributeName: GSI1SK
          AttributeType: S

      KeySchema:

        - AttributeName: PK
          KeyType: HASH

        - AttributeName: SK
          KeyType: RANGE

      GlobalSecondaryIndexes:
        - IndexName: GSI1
          KeySchema:

            - AttributeName: GSI1PK
              KeyType: HASH

            - AttributeName: GSI1SK
              KeyType: RANGE

          Projection:
            ProjectionType: ALL

