Module: S3Sample
Description: A sample module integrating with S3 Bucket events

Variables:

  - Var: MyFirstBucket
    Description: The S3 Bucket the function is listening to
    Resource:
      Type: AWS::S3::Bucket
      Allow: ReadWrite

  - Var: MySecondBucket
    Description: The S3 Bucket the function is listening to
    Resource:
      Type: AWS::S3::Bucket
      Allow: ReadWrite

Functions:

  - Function: MyFunction
    Description: This function is invoked by an S3 Bucket event
    Memory: 128
    Timeout: 30
    Sources:

      # listen to `s3:ObjectCreated:*` on the bucket
      - S3: MyFirstBucket

      # listen to custom events on specific S3 keys
      - S3: MySecondBucket
        Events:
          - "s3:ObjectCreated:*"
          - "s3:ObjectRemoved:*"
        Prefix: images/
        Suffix: .png
