Module: Demo
Description: LambdaSharp Demo

Inputs:

  - Input: SlackToken
    Description: Slack verification token
    Scope: SlackCommand
    Default: ""

Outputs:

  - Output: NotifyRecorderTopic
    Description: The topic that the lambda function subscribes to record messages
    Value: !Ref SnsTopic

Variables:

  - Var: MessageTable
    Scope: "*"
    Description: DynamoDB table for storing received messages
    Resource:
      Type: AWS::DynamoDB::Table
      Allow: ReadWrite
      Properties:
        AttributeDefinitions:
          - AttributeName: MessageId
            AttributeType: S
        KeySchema:
          - AttributeName: MessageId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

  - Var: SnsTopic
    Description: The topic that the lambda function subscribes to record messages
    Resource:
      Type: AWS::SNS::Topic
      Allow: Subscribe

  - Var: UsagePlan
    Description: Limit usage for REST API
    Resource:
      Type: AWS::ApiGateway::UsagePlan
      Properties:
        UsagePlanName: DemoUsagePlan
        ApiStages:
          - ApiId: !Ref ModuleRestApi
            Stage: !Ref ModuleRestApiStage
        Description: Sample usage plan for REST API
        Quota:
          Limit: 500
          Period: MONTH

Functions:

  - Function: RecordMessage
    Description: Record message in a DynamoDB table
    Memory: 128
    Timeout: 30
    Sources:
      - Topic: SnsTopic

  - Function: SlackCommand
    Description: Respond to slack commands
    Memory: 128
    Timeout: 30
    Sources:
      - SlackCommand: /slack
