Name: Demo

Description: LambdaSharp Demo

Parameters:

  - Name: MessageTable
    Description: DynamoDb table for storing received messages
    Resource:
      Type: AWS::DynamoDB::Table
      Allow: ReadWrite
      Properties:
        AttributeDefinitions:
          - AttributeName: MessageId
            AttributeType: S
        KeySchema:
          - AttributeName: MessageId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

  - Name: SnsTopic
    Description: The topic that the lambda function subscribes to record messages
    Export: NotifyRecorderTopic
    Resource:
      Type: AWS::SNS::Topic
      Allow: Subscribe

  - Name: SqsQueue
    Resource:
      Type: AWS::SQS::Queue
      Allow: Receive
      Properties:
        VisibilityTimeout: 600

Functions:

  - Name: RecordMessage
    Description: Record message in a DynamoDB table
    Memory: 128
    Timeout: 30
    Sources:
      - Topic: SnsTopic

  - Name: SlackCommand
    Description: Respond to slack commands
    Memory: 128
    Timeout: 30
    Sources:
      - SlackCommand: /slack
