/*
 * LambdaSharp (λ#)
 * Copyright (C) 2018-2019
 * lambdasharp.net
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

namespace LambdaSharp.Finalizer {

    /// <summary>
    /// The <see cref="FinalizerProperties"/> class describes the LambdaSharp <i>Finalizer</i> resource properties.
    /// These properties are automatically set by the LambdaSharp compiler.
    /// </summary>
    public class FinalizerProperties {

        //--- Properties ---

        /// <summary>
        /// The <see cref="DeploymentChecksum"/> holds the deployment checksum generated by the LambdaSharp compiler.
        /// </summary>
        /// <value>The compiler generated checksum of the current deployment.</value>
        public string DeploymentChecksum { get; set; }

        /// <summary>
        /// The <see cref="ModuleVersion"/> holds the LambdaSharp module version.
        /// </summary>
        /// <value>The module version.</value>
        public string ModuleVersion { get; set; }
    }
}