AWSTemplateFormatVersion: 2010-09-09

Description: LambdaSharpTool Settings

Parameters:

  DeploymentBucketName:
    Type: String
    Description: S3 bucket name to be used for deployments by LambdaSharpTool (if blank, an S3 bucket is created)
    AllowedPattern: '[a-z0-9\-]*'
    ConstraintDescription: Must only contain lowercase alphanumeric characters or left blank

  DeploymentBucketPath:
    Type: String
    Description: S3 key prefix to be used for deployments by LambdaSharpTool

  DeploymentNotificationTopicArn:
    Type: String
    Description: SNS topic for CloudFormation notifications used by LambdaSharpTool (if blank, an SNS topic is created)
    AllowedPattern: '(arn:aws:sns:.*)?'
    ConstraintDescription: Must be an SNS topic ARN or left blank

  LambdaSharpToolVersion:
    Type: String
    Description: LambdaSharpTool version
    AllowedPattern: '\d+.\d+(.\d+(.\d+)?)?'
    ConstraintDescription: 'Version number must have format: Major.Minor[.Build[.Revision]]'

  LambdaSharpToolProfile:
    Type: String
    Description: LambdaSharpTool profile
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9_\-]*'
    ConstraintDescription: Must begin with a valid identifier

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: LambdaSharp Tool Settings
        Parameters:
          - LambdaSharpToolProfile
          - LambdaSharpToolVersion
      - Label:
          default: LambdaSharp Deployment Settings
        Parameters:
          - DeploymentBucketName
          - DeploymentBucketPath
          - DeploymentNotificationTopicArn
    ParameterLabels:
      LambdaSharpToolProfile:
        default: Profile Name
      LambdaSharpToolVersion:
        default: Version
      DeploymentBucketName:
        default: S3 Bucket Name
      DeploymentBucketPath:
        default: S3 Bucket Path
      DeploymentNotificationTopicArn:
        default: SNS Topic ARN

Conditions:
  CreateDeploymentBucket: !Equals [ !Ref DeploymentBucketName, "" ]
  CreateDeploymentNotificationTopic: !Equals [ !Ref DeploymentNotificationTopicArn, "" ]
  HasDeploymentBucketPath: !Not [ !Equals [ !Ref DeploymentBucketPath, "" ]]

Resources:

  # LambdaSharpTool settings
  VersionSsmParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub '/LambdaSharpTool/${LambdaSharpToolProfile}/Version'
      Description: LambdaSharp module version
      Type: String
      Value: !Ref LambdaSharpToolVersion

  StackNameSsmParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub '/LambdaSharpTool/${LambdaSharpToolProfile}/StackName'
      Description: LambdaSharp CloudFormation stack name
      Type: String
      Value: !Ref AWS::StackName

  StackIdSsmParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub '/LambdaSharpTool/${LambdaSharpToolProfile}/StackId'
      Description: LambdaSharp CloudFormation stack ID
      Type: String
      Value: !Ref AWS::StackId

  # S3 Deployment Bucket & Path
  DeploymentBucket:
    Type: AWS::S3::Bucket
    Condition: CreateDeploymentBucket

  DeploymentBucketNameSsmParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub '/LambdaSharpTool/${LambdaSharpToolProfile}/DeploymentBucketName'
      Description: S3 bucket name to install modules
      Type: String
      Value: !If [
        CreateDeploymentBucket,
        !Ref DeploymentBucket,
        !Ref DeploymentBucketName
      ]

  DeploymentBucketPathSsmParameter:
    Type: AWS::SSM::Parameter
    Condition: HasDeploymentBucketPath
    Properties:
      Name: !Sub '/LambdaSharpTool/${LambdaSharpToolProfile}/DeploymentBucketPath'
      Description: S3 key prefix to install modules
      Type: String
      Value: !Ref DeploymentBucketPath

  # SNS CloudFormation Notification Topic
  DeploymentNotificationTopic:
    Type: AWS::SNS::Topic
    Condition: CreateDeploymentNotificationTopic

  DeploymentNotificationTopicSsmParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub '/LambdaSharpTool/${LambdaSharpToolProfile}/DeploymentNotificationTopicArn'
      Description: SNS topic for CloudFormation notifications
      Type: String
      Value: !If [
        CreateDeploymentNotificationTopic,
        !Ref DeploymentNotificationTopic,
        !Ref DeploymentNotificationTopicArn
      ]
