Module: SqsSample
Description: A sample module using SQS queues

Variables:

  - Var: MyFirstQueue
    Description: A sample SQS queue
    Resource:
      Type: AWS::SQS::Queue
      Allow: Receive

  - Var: MySecondQueue
    Description: A sample SQS queue
    Resource:
      Type: AWS::SQS::Queue
      Allow: Receive

Functions:

  - Function: MyFunction
    Description: This function is invoked by an SQS queue
    Memory: 128
    Timeout: 15
    Sources:
      - Sqs: MyFirstQueue
      - Sqs: MySecondQueue
        BatchSize: 1
