name: LambdaSharp CI/CD

on:
  push:
    branches:
      - main
      - v*
      - WIP-v*
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.301

      - name: Test LambdaSharp.CloudFormation
        run: dotnet test --configuration Release --verbosity normal Tests/Tests.LambdaSharp.CloudFormation

      - name: Test LambdaSharp.Modules
        run: dotnet test --configuration Release --verbosity normal Tests/Tests.LambdaSharp.Modules

      - name: Test LambdaSharp.Compiler
        run: dotnet test --configuration Release --verbosity normal Tests/Tests.LambdaSharp.Compiler

      - name: Test LambdaSharp.Tool
        run: dotnet test --configuration Release --verbosity normal Tests/Tests.LambdaSharp.Tool

      - name: Test LambdaSharp
        run: dotnet test --configuration Release --verbosity normal Tests/Tests.LambdaSharp

      - name: Test LambdaSharp.Core
        run: dotnet test --configuration Release --verbosity normal Modules/LambdaSharp.Core/Tests/ProcessLogEventsTests
        env:
          LAMBDASHARP: $HOME
